version: '3.8'

services:
  stats-server:
    build: statistics/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  stats-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

  ewm-service:
    build: main-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      MAIN_SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/main_service
      MAIN_SPRING_DATASOURCE_USERNAME: main_service
      MAIN_SPRING_DATASOURCE_PASSWORD: main_service
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: main_service
      POSTGRES_PASSWORD: main_service