CREATE TABLE IF NOT EXISTS hit
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     varchar(127)                            NOT NULL,
    ip      varchar(45)                             NOT NULL,
    uri     varchar(127)                            NOT NULL,
    created timestamp                               NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);